### ISSUE TITLE
[Meta] Beta releases

### ISSUE THREAD

**Issue by Agrair** [TUA-Team/ROI#3]
Just an issue for beta releases to be downloaded by ROI users.

**Comment by Agrair** [comment]
https://github.com/TUA-Team/ROI/files/3934706/ROI.zip

**Comment by Plantterror** [comment]
👀

**Comment by Agrair** [comment]
https://stackoverflow.com/questions/520347/how-do-i-check-for-a-network-connection

**Comment by Agrair** [comment]
[ROI.zip](https://github.com/TUA-Team/ROI/files/3935741/ROI.zip)

**Comment by Agrair** [comment]
https://github.com/TUA-Team/ROI/files/4202234/ROI.zip

**Comment by Agrair** [comment]
Ignore [Mods.zip](https://github.com/TUA-Team/ROI/files/5013108/Mods.zip)

**Comment by Agrair** [comment]
[ROI.zip](https://github.com/TUA-Team/ROI/files/5287666/ROI.zip)

**Comment by Agrair** [comment]
Closing this because I think it'd be better to use actual beta releases.
